version: '3.9'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - '8080:8080'
  postgres:
    image: postgres:13.4
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    ports:
      - '5432:5432'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready',
          '--dbname=postgres',
          '--host=postgres',
          '--port=5432',
          '--username=postgres'
        ]
      interval: 10s
      timeout: 2s
      retries: 10
